packages:
  - apps/*
  - packages/*
  - packages/plugins/*
minimumReleaseAge: 1440
allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
patchedDependencies:
  '@tailwindcss/node@4.3.0': patches/@tailwindcss__node@4.3.0.patch
