/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as WWorkspaceSlugIndexRouteImport } from './routes/w.$workspaceSlug/index'
import { Route as WWorkspaceSlugSettingsRouteImport } from './routes/w.$workspaceSlug/settings'
import { Route as WWorkspaceSlugBoardsBoardIdRouteImport } from './routes/w.$workspaceSlug/boards.$boardId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceSlugIndexRoute = WWorkspaceSlugIndexRouteImport.update({
  id: '/w/$workspaceSlug/',
  path: '/w/$workspaceSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceSlugSettingsRoute = WWorkspaceSlugSettingsRouteImport.update({
  id: '/w/$workspaceSlug/settings',
  path: '/w/$workspaceSlug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceSlugBoardsBoardIdRoute =
  WWorkspaceSlugBoardsBoardIdRouteImport.update({
    id: '/w/$workspaceSlug/boards/$boardId',
    path: '/w/$workspaceSlug/boards/$boardId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$workspaceSlug/settings': typeof WWorkspaceSlugSettingsRoute
  '/w/$workspaceSlug/': typeof WWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/boards/$boardId': typeof WWorkspaceSlugBoardsBoardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$workspaceSlug/settings': typeof WWorkspaceSlugSettingsRoute
  '/w/$workspaceSlug': typeof WWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/boards/$boardId': typeof WWorkspaceSlugBoardsBoardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$workspaceSlug/settings': typeof WWorkspaceSlugSettingsRoute
  '/w/$workspaceSlug/': typeof WWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/boards/$boardId': typeof WWorkspaceSlugBoardsBoardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/invite/$token'
    | '/w/$workspaceSlug/settings'
    | '/w/$workspaceSlug/'
    | '/w/$workspaceSlug/boards/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/invite/$token'
    | '/w/$workspaceSlug/settings'
    | '/w/$workspaceSlug'
    | '/w/$workspaceSlug/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/invite/$token'
    | '/w/$workspaceSlug/settings'
    | '/w/$workspaceSlug/'
    | '/w/$workspaceSlug/boards/$boardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  InviteTokenRoute: typeof InviteTokenRoute
  WWorkspaceSlugSettingsRoute: typeof WWorkspaceSlugSettingsRoute
  WWorkspaceSlugIndexRoute: typeof WWorkspaceSlugIndexRoute
  WWorkspaceSlugBoardsBoardIdRoute: typeof WWorkspaceSlugBoardsBoardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceSlug/': {
      id: '/w/$workspaceSlug/'
      path: '/w/$workspaceSlug'
      fullPath: '/w/$workspaceSlug/'
      preLoaderRoute: typeof WWorkspaceSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceSlug/settings': {
      id: '/w/$workspaceSlug/settings'
      path: '/w/$workspaceSlug/settings'
      fullPath: '/w/$workspaceSlug/settings'
      preLoaderRoute: typeof WWorkspaceSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceSlug/boards/$boardId': {
      id: '/w/$workspaceSlug/boards/$boardId'
      path: '/w/$workspaceSlug/boards/$boardId'
      fullPath: '/w/$workspaceSlug/boards/$boardId'
      preLoaderRoute: typeof WWorkspaceSlugBoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
  WWorkspaceSlugSettingsRoute: WWorkspaceSlugSettingsRoute,
  WWorkspaceSlugIndexRoute: WWorkspaceSlugIndexRoute,
  WWorkspaceSlugBoardsBoardIdRoute: WWorkspaceSlugBoardsBoardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
