// This file is auto-generated by scripts/sync-plugins.mjs.
// Do not edit it by hand.

import { calendarBoardServerPlugin } from "../../plugins/calendar-board/src/server.ts";
import { coreKanbanServerPlugin } from "../../plugins/core-kanban/src/server.ts";
import { focusToolsServerPlugin } from "../../plugins/focus-tools/src/server.ts";
import { taskBoardServerPlugin } from "../../plugins/task-board/src/server.ts";

export const generatedBuiltinServerPlugins = [
  calendarBoardServerPlugin,
  coreKanbanServerPlugin,
  focusToolsServerPlugin,
  taskBoardServerPlugin,
];
