// This file is auto-generated by scripts/sync-plugins.mjs.
// Do not edit it by hand.

import { calendarBoardPlugin } from "../../plugins/calendar-board/src/index.tsx";
import { coreKanbanPlugin } from "../../plugins/core-kanban/src/index.tsx";
import { focusToolsPlugin } from "../../plugins/focus-tools/src/index.tsx";
import { taskBoardPlugin } from "../../plugins/task-board/src/index.tsx";

export const generatedBuiltinPlugins = [
  calendarBoardPlugin,
  coreKanbanPlugin,
  focusToolsPlugin,
  taskBoardPlugin,
];
