import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  assertPluginPackagePolicy,
  getPluginExportPath,
  pluginIdFromPackageName,
} from "./plugin-package-policy.mjs";

const REQUIRED_BUILTIN_PLUGIN_IDS = ["core-kanban", "calendar-board"];

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const pluginsRoot = path.join(repoRoot, "packages", "plugins");
const clientOutputPath = path.join(
  repoRoot,
  "packages",
  "plugin-runtime",
  "src",
  "builtins.client.generated.ts",
);
const serverOutputPath = path.join(
  repoRoot,
  "packages",
  "plugin-runtime",
  "src",
  "builtins.server.generated.ts",
);

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function readPluginExportName(entryPath, defineFunctionName) {
  const source = fs.readFileSync(entryPath, "utf8");
  const pattern = new RegExp(
    `export const (\\w+)\\s*=\\s*${defineFunctionName}\\b`,
    "g",
  );
  const matches = [...source.matchAll(pattern)];

  if (matches.length !== 1) {
    throw new Error(
      `Expected exactly one exported ${defineFunctionName}() constant in ${entryPath}, found ${matches.length}`,
    );
  }

  return matches[0][1];
}

function toPosixPath(filePath) {
  return filePath.split(path.sep).join("/");
}

function relativeImport(fromFile, toFile) {
  const relativePath = path.relative(path.dirname(fromFile), toFile);
  const normalized = toPosixPath(relativePath);
  return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

function listPluginPackages() {
  return fs
    .readdirSync(pluginsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(pluginsRoot, entry.name))
    .map((packageDir) => {
      const packageJsonPath = path.join(packageDir, "package.json");
      const packageJson = readJson(packageJsonPath);
      const packageName = String(packageJson.name);
      const policy = assertPluginPackagePolicy(packageDir);
      const pluginId = pluginIdFromPackageName(packageName);
      if (!pluginId) {
        throw new Error(`Expected plugin package name to start with @plank/plugin-, got ${packageName}`);
      }
      const entryPath = getPluginExportPath(packageDir, packageJson, ".");
      const serverEntryPath = getPluginExportPath(packageDir, packageJson, "./server");
      if (!entryPath || !serverEntryPath) {
        throw new Error(policy.diagnostics.join("\n"));
      }
      const exportName = readPluginExportName(entryPath, "defineClientPlugin");
      const serverExportName = readPluginExportName(
        serverEntryPath,
        "defineServerPlugin",
      );

      return {
        packageDir,
        packageName,
        pluginId,
        entryPath,
        exportName,
        serverEntryPath,
        serverExportName,
      };
    })
    .sort((left, right) => left.pluginId.localeCompare(right.pluginId));
}

function assertRequiredPluginsPresent(pluginPackages) {
  const available = new Set(pluginPackages.map((pluginPackage) => pluginPackage.pluginId));
  const missing = REQUIRED_BUILTIN_PLUGIN_IDS.filter((pluginId) => !available.has(pluginId));

  if (missing.length > 0) {
    throw new Error(
      `Missing required builtin plugin package(s): ${missing.join(", ")}`,
    );
  }
}

function renderGeneratedClientFile(pluginPackages) {
  const clientImports = pluginPackages.map((pluginPackage) => {
    const importPath = relativeImport(clientOutputPath, pluginPackage.entryPath);
    return `import { ${pluginPackage.exportName} } from "${importPath}";`;
  });
  const clientPluginList = pluginPackages.map((pluginPackage) => pluginPackage.exportName);

  return `${[
    "// This file is auto-generated by scripts/sync-plugins.mjs.",
    "// Do not edit it by hand.",
    "",
    ...clientImports,
    "",
    "export const generatedBuiltinClientPlugins = [",
    ...clientPluginList.map((pluginName) => `  ${pluginName},`),
    "];",
    "",
  ].join("\n")}`;
}

function renderGeneratedServerFile(pluginPackages) {
  const serverImports = pluginPackages.map((pluginPackage) => {
    const importPath = relativeImport(serverOutputPath, pluginPackage.serverEntryPath);
    return `import { ${pluginPackage.serverExportName} } from "${importPath}";`;
  });
  const serverPluginList = pluginPackages.map(
    (pluginPackage) => pluginPackage.serverExportName,
  );

  return `${[
    "// This file is auto-generated by scripts/sync-plugins.mjs.",
    "// Do not edit it by hand.",
    "",
    ...serverImports,
    "",
    "export const generatedBuiltinServerPlugins = [",
    ...serverPluginList.map((pluginName) => `  ${pluginName},`),
    "];",
    "",
  ].join("\n")}`;
}

function writeIfChanged(filePath, nextContent) {
  const currentContent = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, "utf8")
    : null;

  if (currentContent === nextContent) {
    return false;
  }

  fs.writeFileSync(filePath, nextContent);
  return true;
}

const pluginPackages = listPluginPackages();
assertRequiredPluginsPresent(pluginPackages);

const didClientChange = writeIfChanged(
  clientOutputPath,
  renderGeneratedClientFile(pluginPackages),
);
const didServerChange = writeIfChanged(
  serverOutputPath,
  renderGeneratedServerFile(pluginPackages),
);
const didChange = didClientChange || didServerChange;

console.log(
  didChange
    ? `Synced builtin plugin registry for ${pluginPackages.length} plugin package(s).`
    : `Builtin plugin registry already up to date for ${pluginPackages.length} plugin package(s).`,
);
