import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REQUIRED_BUILTIN_PLUGIN_IDS = ["core-kanban", "calendar-board"];

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const pluginsRoot = path.join(repoRoot, "packages", "plugins");
const outputPath = path.join(
  repoRoot,
  "packages",
  "plugin-runtime",
  "src",
  "builtins.generated.ts",
);

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function readPluginEntryPath(packageDir, packageJson) {
  const entry =
    typeof packageJson.exports === "string"
      ? packageJson.exports
      : packageJson.exports?.["."];

  if (typeof entry !== "string") {
    throw new Error(
      `Plugin package ${packageJson.name ?? packageDir} must expose "." as a string export`,
    );
  }

  return path.join(packageDir, entry.replace(/^\.\//, ""));
}

function readPluginExportName(entryPath) {
  const source = fs.readFileSync(entryPath, "utf8");
  const matches = [...source.matchAll(/export const (\w+)\s*=\s*definePlugin\b/g)];

  if (matches.length !== 1) {
    throw new Error(
      `Expected exactly one exported definePlugin() constant in ${entryPath}, found ${matches.length}`,
    );
  }

  return matches[0][1];
}

function toPosixPath(filePath) {
  return filePath.split(path.sep).join("/");
}

function relativeImport(fromFile, toFile) {
  const relativePath = path.relative(path.dirname(fromFile), toFile);
  const normalized = toPosixPath(relativePath);
  return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

function pluginIdFromPackageName(packageName) {
  const prefix = "@plank/plugin-";
  if (!packageName.startsWith(prefix)) {
    throw new Error(
      `Expected plugin package name to start with ${prefix}, got ${packageName}`,
    );
  }
  return packageName.slice(prefix.length);
}

function listPluginPackages() {
  return fs
    .readdirSync(pluginsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(pluginsRoot, entry.name))
    .map((packageDir) => {
      const packageJsonPath = path.join(packageDir, "package.json");
      const packageJson = readJson(packageJsonPath);
      const packageName = String(packageJson.name);
      const pluginId = pluginIdFromPackageName(packageName);
      const entryPath = readPluginEntryPath(packageDir, packageJson);
      const exportName = readPluginExportName(entryPath);

      return {
        packageDir,
        packageName,
        pluginId,
        entryPath,
        exportName,
      };
    })
    .sort((left, right) => left.pluginId.localeCompare(right.pluginId));
}

function assertRequiredPluginsPresent(pluginPackages) {
  const available = new Set(pluginPackages.map((pluginPackage) => pluginPackage.pluginId));
  const missing = REQUIRED_BUILTIN_PLUGIN_IDS.filter((pluginId) => !available.has(pluginId));

  if (missing.length > 0) {
    throw new Error(
      `Missing required builtin plugin package(s): ${missing.join(", ")}`,
    );
  }
}

function renderGeneratedFile(pluginPackages) {
  const imports = pluginPackages.map((pluginPackage) => {
    const importPath = relativeImport(outputPath, pluginPackage.entryPath);
    return `import { ${pluginPackage.exportName} } from "${importPath}";`;
  });

  const pluginList = pluginPackages.map((pluginPackage) => pluginPackage.exportName);

  return `${[
    "// This file is auto-generated by scripts/sync-plugins.mjs.",
    "// Do not edit it by hand.",
    "",
    ...imports,
    "",
    "export const generatedBuiltinPlugins = [",
    ...pluginList.map((pluginName) => `  ${pluginName},`),
    "];",
    "",
  ].join("\n")}`;
}

function writeIfChanged(filePath, nextContent) {
  const currentContent = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, "utf8")
    : null;

  if (currentContent === nextContent) {
    return false;
  }

  fs.writeFileSync(filePath, nextContent);
  return true;
}

const pluginPackages = listPluginPackages();
assertRequiredPluginsPresent(pluginPackages);

const didChange = writeIfChanged(outputPath, renderGeneratedFile(pluginPackages));

console.log(
  didChange
    ? `Synced builtin plugin registry for ${pluginPackages.length} plugin package(s).`
    : `Builtin plugin registry already up to date for ${pluginPackages.length} plugin package(s).`,
);
